package com.aolc.designer.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _AcctUser was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AcctUser extends CayenneDataObject {

    public static final String AVATAR_PROPERTY = "avatar";
    public static final String CATEGORY_PROPERTY = "category";
    public static final String CREATE_TIME_PROPERTY = "createTime";
    public static final String PASSWORD_PROPERTY = "password";
    public static final String SID_PROPERTY = "sid";
    public static final String STATUS_PROPERTY = "status";
    public static final String TYPE_PROPERTY = "type";
    public static final String UNIQUEID_PROPERTY = "uniqueid";
    public static final String UPLOAD_PROPERTY = "upload";
    public static final String USERNAME_PROPERTY = "username";
    public static final String VERIFY_TIME_PROPERTY = "verifyTime";

    public static final String SID_PK_COLUMN = "sid";

    public void setAvatar(String avatar) {
        writeProperty(AVATAR_PROPERTY, avatar);
    }
    public String getAvatar() {
        return (String)readProperty(AVATAR_PROPERTY);
    }

    public void setCategory(String category) {
        writeProperty(CATEGORY_PROPERTY, category);
    }
    public String getCategory() {
        return (String)readProperty(CATEGORY_PROPERTY);
    }

    public void setCreateTime(Date createTime) {
        writeProperty(CREATE_TIME_PROPERTY, createTime);
    }
    public Date getCreateTime() {
        return (Date)readProperty(CREATE_TIME_PROPERTY);
    }

    public void setPassword(String password) {
        writeProperty(PASSWORD_PROPERTY, password);
    }
    public String getPassword() {
        return (String)readProperty(PASSWORD_PROPERTY);
    }

    public void setSid(Integer sid) {
        writeProperty(SID_PROPERTY, sid);
    }
    public Integer getSid() {
        return (Integer)readProperty(SID_PROPERTY);
    }

    public void setStatus(String status) {
        writeProperty(STATUS_PROPERTY, status);
    }
    public String getStatus() {
        return (String)readProperty(STATUS_PROPERTY);
    }

    public void setType(String type) {
        writeProperty(TYPE_PROPERTY, type);
    }
    public String getType() {
        return (String)readProperty(TYPE_PROPERTY);
    }

    public void setUniqueid(String uniqueid) {
        writeProperty(UNIQUEID_PROPERTY, uniqueid);
    }
    public String getUniqueid() {
        return (String)readProperty(UNIQUEID_PROPERTY);
    }

    public void setUpload(Integer upload) {
        writeProperty(UPLOAD_PROPERTY, upload);
    }
    public Integer getUpload() {
        return (Integer)readProperty(UPLOAD_PROPERTY);
    }

    public void setUsername(String username) {
        writeProperty(USERNAME_PROPERTY, username);
    }
    public String getUsername() {
        return (String)readProperty(USERNAME_PROPERTY);
    }

    public void setVerifyTime(Date verifyTime) {
        writeProperty(VERIFY_TIME_PROPERTY, verifyTime);
    }
    public Date getVerifyTime() {
        return (Date)readProperty(VERIFY_TIME_PROPERTY);
    }

}
