package com.aolc.designer.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _AcctUserCompany was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AcctUserCompany extends CayenneDataObject {

    public static final String ADDRESS_PROPERTY = "address";
    public static final String BRAND_NAME_PROPERTY = "brandName";
    public static final String BRAND_NUM_PROPERTY = "brandNum";
    public static final String BUSINESS_CONTACT_CARD_PROPERTY = "businessContactCard";
    public static final String BUSINESS_LICENCE_PROPERTY = "businessLicence";
    public static final String CONNECT_TELEPHONE_PROPERTY = "connectTelephone";
    public static final String EMAIL_PROPERTY = "email";
    public static final String ENTERPRISE_NATURE_PROPERTY = "enterpriseNature";
    public static final String NAME_PROPERTY = "name";
    public static final String ORGANIZATION_CODE_CERTIFICATE_PROPERTY = "organizationCodeCertificate";
    public static final String REGISTION_PLACE_PROPERTY = "registionPlace";
    public static final String SIZE_PROPERTY = "size";
    public static final String TAX_REGISTRATION_CERTIFICATE_PROPERTY = "taxRegistrationCertificate";
    public static final String TELEPHONE_PROPERTY = "telephone";
    public static final String UNIQUEID_PROPERTY = "uniqueid";
    public static final String USER_UNIQUEID_PROPERTY = "userUniqueid";

    public static final String UNIQUEID_PK_COLUMN = "uniqueid";

    public void setAddress(String address) {
        writeProperty(ADDRESS_PROPERTY, address);
    }
    public String getAddress() {
        return (String)readProperty(ADDRESS_PROPERTY);
    }

    public void setBrandName(String brandName) {
        writeProperty(BRAND_NAME_PROPERTY, brandName);
    }
    public String getBrandName() {
        return (String)readProperty(BRAND_NAME_PROPERTY);
    }

    public void setBrandNum(String brandNum) {
        writeProperty(BRAND_NUM_PROPERTY, brandNum);
    }
    public String getBrandNum() {
        return (String)readProperty(BRAND_NUM_PROPERTY);
    }

    public void setBusinessContactCard(String businessContactCard) {
        writeProperty(BUSINESS_CONTACT_CARD_PROPERTY, businessContactCard);
    }
    public String getBusinessContactCard() {
        return (String)readProperty(BUSINESS_CONTACT_CARD_PROPERTY);
    }

    public void setBusinessLicence(String businessLicence) {
        writeProperty(BUSINESS_LICENCE_PROPERTY, businessLicence);
    }
    public String getBusinessLicence() {
        return (String)readProperty(BUSINESS_LICENCE_PROPERTY);
    }

    public void setConnectTelephone(String connectTelephone) {
        writeProperty(CONNECT_TELEPHONE_PROPERTY, connectTelephone);
    }
    public String getConnectTelephone() {
        return (String)readProperty(CONNECT_TELEPHONE_PROPERTY);
    }

    public void setEmail(String email) {
        writeProperty(EMAIL_PROPERTY, email);
    }
    public String getEmail() {
        return (String)readProperty(EMAIL_PROPERTY);
    }

    public void setEnterpriseNature(String enterpriseNature) {
        writeProperty(ENTERPRISE_NATURE_PROPERTY, enterpriseNature);
    }
    public String getEnterpriseNature() {
        return (String)readProperty(ENTERPRISE_NATURE_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setOrganizationCodeCertificate(String organizationCodeCertificate) {
        writeProperty(ORGANIZATION_CODE_CERTIFICATE_PROPERTY, organizationCodeCertificate);
    }
    public String getOrganizationCodeCertificate() {
        return (String)readProperty(ORGANIZATION_CODE_CERTIFICATE_PROPERTY);
    }

    public void setRegistionPlace(String registionPlace) {
        writeProperty(REGISTION_PLACE_PROPERTY, registionPlace);
    }
    public String getRegistionPlace() {
        return (String)readProperty(REGISTION_PLACE_PROPERTY);
    }

    public void setSize(String size) {
        writeProperty(SIZE_PROPERTY, size);
    }
    public String getSize() {
        return (String)readProperty(SIZE_PROPERTY);
    }

    public void setTaxRegistrationCertificate(String taxRegistrationCertificate) {
        writeProperty(TAX_REGISTRATION_CERTIFICATE_PROPERTY, taxRegistrationCertificate);
    }
    public String getTaxRegistrationCertificate() {
        return (String)readProperty(TAX_REGISTRATION_CERTIFICATE_PROPERTY);
    }

    public void setTelephone(String telephone) {
        writeProperty(TELEPHONE_PROPERTY, telephone);
    }
    public String getTelephone() {
        return (String)readProperty(TELEPHONE_PROPERTY);
    }

    public void setUniqueid(String uniqueid) {
        writeProperty(UNIQUEID_PROPERTY, uniqueid);
    }
    public String getUniqueid() {
        return (String)readProperty(UNIQUEID_PROPERTY);
    }

    public void setUserUniqueid(String userUniqueid) {
        writeProperty(USER_UNIQUEID_PROPERTY, userUniqueid);
    }
    public String getUserUniqueid() {
        return (String)readProperty(USER_UNIQUEID_PROPERTY);
    }

}
