package com.aolc.designer.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _AcctUserPro was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AcctUserPro extends CayenneDataObject {

    public static final String ADDRESS_PROPERTY = "address";
    public static final String AGENT_PROPERTY = "agent";
    public static final String BIRTH_PLACE_PROPERTY = "birthPlace";
    public static final String BIRTH_TIME_PROPERTY = "birthTime";
    public static final String BRAND_NAME_PROPERTY = "brandName";
    public static final String COLLEGE_PROPERTY = "college";
    public static final String COUNTRY_PROPERTY = "country";
    public static final String COUNTRY_CODE_PROPERTY = "countryCode";
    public static final String DESIGN_STYLE_PROPERTY = "designStyle";
    public static final String DESIGN_TYPE_PROPERTY = "designType";
    public static final String EMAIL_PROPERTY = "email";
    public static final String EXPERIENCE_PROPERTY = "experience";
    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String GRADUATE_PROPERTY = "graduate";
    public static final String HOME_PAGE_PROPERTY = "homePage";
    public static final String INSTAGRAM_PROPERTY = "instagram";
    public static final String NAME_PROPERTY = "name";
    public static final String OTHER_PROPERTY = "other";
    public static final String PRODUCTION_PROPERTY = "production";
    public static final String PROFESSION_PROPERTY = "profession";
    public static final String REGITRATION_PLACE_PROPERTY = "regitrationPlace";
    public static final String REGITRATION_TIME_PROPERTY = "regitrationTime";
    public static final String RESUME_PROPERTY = "resume";
    public static final String SCHOOL_PROPERTY = "school";
    public static final String TELEPHONE_PROPERTY = "telephone";
    public static final String UNIQUEID_PROPERTY = "uniqueid";
    public static final String USER_BACKGROUND_PROPERTY = "userBackground";
    public static final String USER_UNIQUEID_PROPERTY = "userUniqueid";
    public static final String WORKS_PROPERTY = "works";

    public static final String UNIQUEID_PK_COLUMN = "uniqueid";

    public void setAddress(String address) {
        writeProperty(ADDRESS_PROPERTY, address);
    }
    public String getAddress() {
        return (String)readProperty(ADDRESS_PROPERTY);
    }

    public void setAgent(String agent) {
        writeProperty(AGENT_PROPERTY, agent);
    }
    public String getAgent() {
        return (String)readProperty(AGENT_PROPERTY);
    }

    public void setBirthPlace(String birthPlace) {
        writeProperty(BIRTH_PLACE_PROPERTY, birthPlace);
    }
    public String getBirthPlace() {
        return (String)readProperty(BIRTH_PLACE_PROPERTY);
    }

    public void setBirthTime(Date birthTime) {
        writeProperty(BIRTH_TIME_PROPERTY, birthTime);
    }
    public Date getBirthTime() {
        return (Date)readProperty(BIRTH_TIME_PROPERTY);
    }

    public void setBrandName(String brandName) {
        writeProperty(BRAND_NAME_PROPERTY, brandName);
    }
    public String getBrandName() {
        return (String)readProperty(BRAND_NAME_PROPERTY);
    }

    public void setCollege(String college) {
        writeProperty(COLLEGE_PROPERTY, college);
    }
    public String getCollege() {
        return (String)readProperty(COLLEGE_PROPERTY);
    }

    public void setCountry(String country) {
        writeProperty(COUNTRY_PROPERTY, country);
    }
    public String getCountry() {
        return (String)readProperty(COUNTRY_PROPERTY);
    }

    public void setCountryCode(String countryCode) {
        writeProperty(COUNTRY_CODE_PROPERTY, countryCode);
    }
    public String getCountryCode() {
        return (String)readProperty(COUNTRY_CODE_PROPERTY);
    }

    public void setDesignStyle(String designStyle) {
        writeProperty(DESIGN_STYLE_PROPERTY, designStyle);
    }
    public String getDesignStyle() {
        return (String)readProperty(DESIGN_STYLE_PROPERTY);
    }

    public void setDesignType(String designType) {
        writeProperty(DESIGN_TYPE_PROPERTY, designType);
    }
    public String getDesignType() {
        return (String)readProperty(DESIGN_TYPE_PROPERTY);
    }

    public void setEmail(String email) {
        writeProperty(EMAIL_PROPERTY, email);
    }
    public String getEmail() {
        return (String)readProperty(EMAIL_PROPERTY);
    }

    public void setExperience(String experience) {
        writeProperty(EXPERIENCE_PROPERTY, experience);
    }
    public String getExperience() {
        return (String)readProperty(EXPERIENCE_PROPERTY);
    }

    public void setFirstName(String firstName) {
        writeProperty(FIRST_NAME_PROPERTY, firstName);
    }
    public String getFirstName() {
        return (String)readProperty(FIRST_NAME_PROPERTY);
    }

    public void setGraduate(String graduate) {
        writeProperty(GRADUATE_PROPERTY, graduate);
    }
    public String getGraduate() {
        return (String)readProperty(GRADUATE_PROPERTY);
    }

    public void setHomePage(String homePage) {
        writeProperty(HOME_PAGE_PROPERTY, homePage);
    }
    public String getHomePage() {
        return (String)readProperty(HOME_PAGE_PROPERTY);
    }

    public void setInstagram(String instagram) {
        writeProperty(INSTAGRAM_PROPERTY, instagram);
    }
    public String getInstagram() {
        return (String)readProperty(INSTAGRAM_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setOther(String other) {
        writeProperty(OTHER_PROPERTY, other);
    }
    public String getOther() {
        return (String)readProperty(OTHER_PROPERTY);
    }

    public void setProduction(Integer production) {
        writeProperty(PRODUCTION_PROPERTY, production);
    }
    public Integer getProduction() {
        return (Integer)readProperty(PRODUCTION_PROPERTY);
    }

    public void setProfession(String profession) {
        writeProperty(PROFESSION_PROPERTY, profession);
    }
    public String getProfession() {
        return (String)readProperty(PROFESSION_PROPERTY);
    }

    public void setRegitrationPlace(String regitrationPlace) {
        writeProperty(REGITRATION_PLACE_PROPERTY, regitrationPlace);
    }
    public String getRegitrationPlace() {
        return (String)readProperty(REGITRATION_PLACE_PROPERTY);
    }

    public void setRegitrationTime(Date regitrationTime) {
        writeProperty(REGITRATION_TIME_PROPERTY, regitrationTime);
    }
    public Date getRegitrationTime() {
        return (Date)readProperty(REGITRATION_TIME_PROPERTY);
    }

    public void setResume(String resume) {
        writeProperty(RESUME_PROPERTY, resume);
    }
    public String getResume() {
        return (String)readProperty(RESUME_PROPERTY);
    }

    public void setSchool(String school) {
        writeProperty(SCHOOL_PROPERTY, school);
    }
    public String getSchool() {
        return (String)readProperty(SCHOOL_PROPERTY);
    }

    public void setTelephone(String telephone) {
        writeProperty(TELEPHONE_PROPERTY, telephone);
    }
    public String getTelephone() {
        return (String)readProperty(TELEPHONE_PROPERTY);
    }

    public void setUniqueid(String uniqueid) {
        writeProperty(UNIQUEID_PROPERTY, uniqueid);
    }
    public String getUniqueid() {
        return (String)readProperty(UNIQUEID_PROPERTY);
    }

    public void setUserBackground(String userBackground) {
        writeProperty(USER_BACKGROUND_PROPERTY, userBackground);
    }
    public String getUserBackground() {
        return (String)readProperty(USER_BACKGROUND_PROPERTY);
    }

    public void setUserUniqueid(String userUniqueid) {
        writeProperty(USER_UNIQUEID_PROPERTY, userUniqueid);
    }
    public String getUserUniqueid() {
        return (String)readProperty(USER_UNIQUEID_PROPERTY);
    }

    public void setWorks(String works) {
        writeProperty(WORKS_PROPERTY, works);
    }
    public String getWorks() {
        return (String)readProperty(WORKS_PROPERTY);
    }

}
