package com.aolc.designer.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _MstCompanyApplyMapping was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MstCompanyApplyMapping extends CayenneDataObject {

    public static final String CREATE_TIME_PROPERTY = "createTime";
    public static final String EM_UNIQUEID_PROPERTY = "emUniqueid";
    public static final String STATUS_PROPERTY = "status";
    public static final String UNIQUEID_PROPERTY = "uniqueid";
    public static final String USER_UNIQUEID_PROPERTY = "userUniqueid";

    public static final String UNIQUEID_PK_COLUMN = "uniqueid";

    public void setCreateTime(Date createTime) {
        writeProperty(CREATE_TIME_PROPERTY, createTime);
    }
    public Date getCreateTime() {
        return (Date)readProperty(CREATE_TIME_PROPERTY);
    }

    public void setEmUniqueid(String emUniqueid) {
        writeProperty(EM_UNIQUEID_PROPERTY, emUniqueid);
    }
    public String getEmUniqueid() {
        return (String)readProperty(EM_UNIQUEID_PROPERTY);
    }

    public void setStatus(String status) {
        writeProperty(STATUS_PROPERTY, status);
    }
    public String getStatus() {
        return (String)readProperty(STATUS_PROPERTY);
    }

    public void setUniqueid(String uniqueid) {
        writeProperty(UNIQUEID_PROPERTY, uniqueid);
    }
    public String getUniqueid() {
        return (String)readProperty(UNIQUEID_PROPERTY);
    }

    public void setUserUniqueid(String userUniqueid) {
        writeProperty(USER_UNIQUEID_PROPERTY, userUniqueid);
    }
    public String getUserUniqueid() {
        return (String)readProperty(USER_UNIQUEID_PROPERTY);
    }

}
