package com.aolc.designer.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _MstCategory was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MstCategory extends CayenneDataObject {

    public static final String CODE_PROPERTY = "code";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String NODE_UNIQUEID_PROPERTY = "nodeUniqueid";
    public static final String PROJECT_PROPERTY = "project";


    public void setCode(String code) {
        writeProperty(CODE_PROPERTY, code);
    }
    public String getCode() {
        return (String)readProperty(CODE_PROPERTY);
    }

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setNodeUniqueid(String nodeUniqueid) {
        writeProperty(NODE_UNIQUEID_PROPERTY, nodeUniqueid);
    }
    public String getNodeUniqueid() {
        return (String)readProperty(NODE_UNIQUEID_PROPERTY);
    }

    public void setProject(String project) {
        writeProperty(PROJECT_PROPERTY, project);
    }
    public String getProject() {
        return (String)readProperty(PROJECT_PROPERTY);
    }

}
